version: '3.7'

services:

  backend:
    image: appointmentscheduler:1.0.4
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://scheduler-db:5432/scheduler
      - SPRING_DATASOURCE_USERNAME=scheduler
      - SPRING_DATASOURCE_PASSWORD=scheduler
    ports:
      - "8088:8080"
    restart: always
    depends_on:
      - scheduler-db
    networks:
      - appointmentscheduler_network

  scheduler-db:
    image: 'postgres:13.3'
    container_name: scheduler-db
    networks:
      - appointmentscheduler_network
    environment:
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=scheduler
    ports:
      - mode: host
        protocol: tcp
        published: 6432
        target: 5432
    volumes:
      - appointmentscheduler_volume:/var/lib/pgsql
    networks:
      - appointmentscheduler_network

volumes:
  appointmentscheduler_volume:

networks:
  appointmentscheduler_network:
